management:
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8090

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
  file: log/ampota-user.log

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost/ampota_user
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:/db/migration
  cloud.stream:
    bindings:
      auditChannel:
        destination: auditChannel
        binder: local_rabbit
    binders:
      local_rabbit:
        type: rabbit
        environment:
          spring:
            rabbitmq:
              host: xpay-staging.manila.exist.com
              port: 5672
              username: rabbitmq
              password: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka