management:
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8082

spring:
  application:
    name: project
  datasource:
    jdbc-url: jdbc:mysql://localhost/dgtedr_project
    username: root
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:/db/migration/mysql

logging:
  level:
    com.dgtedr: debug
  file: log/dgtedr-project-project.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka