management:
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8082

spring:
  application:
    name: project
  datasource:
    jdbc-url: jdbc:postgresql://localhost/dgtedr_project
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: false
    locations: classpath:/db/migration/mysql

logging:
  level:
    com.dgtedr: debug
  file: log/dgtedr-project-project.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka