management:
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8080

spring:
  application:
    name: gateway

logging:
  level:
    ROOT: info
    com.dgtedr: debug
  file: log/dgtedr-project-gateway.log

eureka:
  instance:
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka