endpoints:
  shutdown:
    enabled: true

management:
  security:
    enabled: false

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/dgtedr_doctor
    username: root
    password: 123qwe
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

logging:
  level:
    ROOT: info
    com.dgtedr: debug
  file: log/dgtedr-doctor.log

flyway:
  enabled: false
  locations: classpath:/db/migration/mysql
